branches:
  only:
    - master

language: python
python:
  - 3.7

services:
  - docker

install:
  - make -C docker/ build

script:
  - make -C docker/ test

after_script:
  - make -C docker/ clean
  - make -C docker/ prune
