version: '3.4'

services:
  pgcom:
    image: pgcom
    container_name: pgcom
    user: user
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PGPASSWORD=postgres
    command: ["tail", "-f", "/dev/null"]

  postgresql:
    image: library/postgres:latest
    container_name: pgcom
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
